<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Roots\BlogPost\Events\" />
      <Folder Include="Roots\Sitemap\Events\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Libraries\Portfolio.Common\Portfolio.Common.csproj" />
    </ItemGroup>

</Project>
