<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Aggregates\BlogPost\Events\" />
      <Folder Include="Aggregates\Shared\" />
      <Folder Include="Aggregates\Sitemap\Events\" />
      <Folder Include="Aggregates\SearchIndex\Enums\" />
      <Folder Include="Aggregates\SearchIndex\Events\" />
      <Folder Include="Aggregates\SearchIndex\ValueObjects\" />
      <Folder Include="Service\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Libraries\Portfolio.Common\Portfolio.Common.csproj" />
    </ItemGroup>

</Project>
