name: PROD_SiteStack
services:
  zacharymunshaw-prod:
    image: site-backend:prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SE_DB_CONN: "host=${SE_PROD_DB_HOST};port=${SE_PROD_DB_PORT};database=${SE_PROD_DB_NAME};username=${SE_PROD_DB_USER};password=${SE_PROD_DB_PASS};"
      SITE_DB_CONN: "host=${SITE_PROD_DB_HOST};port=${SITE_PROD_DB_PORT};database=${SITE_PROD_DB_NAME};username=${SITE_PROD_DB_USER};password=${SITE_PROD_DB_PASS};"
      AI_HOST: "http://172.17.0.1"
      AI_PORT: "1233"
      ASPNETCORE_ENVIRONMENT: Production
      API_PORT: ${PROD_PORT}
      SAFE_MODE: true
      WIPE_ON_START: false
      MIGRATE: false
      SEED_DATABASE: false
    volumes:
      - ./Data/SeedData:/app/data
    ports:
      - ${PROD_PORT}:${PROD_PORT}
    networks:
      - zm-prod-tunnel-net
      - zm-prod-db-net
      - zm-prod-cache-net
  
  cloudflared-prod:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-prod
    restart: always
    entrypoint: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_PROD_TOKEN}
    networks:
      - zm-prod-tunnel-net
  ## Databases
  site-db-prod:
    image: postgres:latest
    container_name: site-database
    restart: always
    command: -p ${SITE_PROD_DB_PORT}
    ports:
      - ${SITE_PROD_DB_PORT}:${SITE_PROD_DB_PORT}
    environment:
      POSTGRES_DB: ${SITE_PROD_DB_NAME}
      POSTGRES_USER: ${SITE_PROD_DB_USER}
      POSTGRES_PASSWORD: ${SITE_PROD_DB_PASS}
    volumes:
      - PROD-site-db:/var/lib/postgresql/data
    networks:
      - zm-prod-db-net
  se-db-prod:
    image: pgvector/pgvector:pg16
    container_name: se-prod-db
    restart: always
    command: -p ${SE_PROD_DB_PORT}
    ports:
      - ${SE_PROD_DB_PORT}:${SE_PROD_DB_PORT}
    environment:
      POSTGRES_DB: ${SE_PROD_DB_NAME}
      POSTGRES_USER: ${SE_PROD_DB_USER}
      POSTGRES_PASSWORD: ${SE_PROD_DB_PASS}
    volumes:
      - PROD-se-db:/var/lib/postgresql/data
    networks:
      - zm-prod-db-net
  anythingllm-prod:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm
    ports:
      - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - PROD-llm:/app/server/storage
    cap_add:
      - SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  zm-prod-tunnel-net:
    driver: bridge
  zm-prod-db-net:
    driver: bridge
  zm-prod-cache-net:
    driver: bridge

volumes:
  PROD-site-db:
  PROD-se-db:
  PROD-cache:
  PROD-llm: