@API_HostAddress = http://localhost:1177

### Send 3 URLs
POST {{API_HostAddress}}/scrape
Accept: application/json
Content-Type: application/json

{
  "page_urls": [
    "example.com",
    "example.org",
    "example.net"
  ]
}

### Send 3 Good URLs and 2 Bad
POST {{API_HostAddress}}/scrape
Accept: application/json
Content-Type: application/json

{
  "page_urls": [
    "example.com",
    "example.org",
    "example.net",
    "Nutty Putty",
    "https://0002112sasd---"
  ]
}

### Send no urls and fail
POST {{API_HostAddress}}/scrape
Accept: application/json
Content-Type: application/json

{
"page_urls": []
}