## WIP
name: SiteDevStack
services:
  backend-dotnet:
    image: site-backend
    restart: always
    build:
      context: .
      dockerfile: DevSiteBackend/Dockerfile
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    entrypoint: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - "${CLOUDFLARED_TOKEN}"
    env_file:
      - .real.env
    networks:
      - tunnel-net
 ## Databases
  ## For site-specific functionality (e.g., Blog Posts, Sign In, API Data, etc.)
  site-db:
    image: postgres:latest
    container_name: site-db
    restart: always
    ports:
      - ${SITE_PORT}:5432
    environment:
      POSTGRES_DB: ${SITE_DB_NAME}
      POSTGRES_USER: ${SITE_DB_USER}
      POSTGRES_PASSWORD: ${SITE_DB_PASS}
    volumes:
      - site_db:/var/lib/postgresql/data
  ## For search engine functionality (e.g., VectorPG, Websites, Sitemaps Etc)
  se-db:
    image:  pgvector/pgvector:pg16
    container_name: se-db
    restart: always
    ports:
      - ${SE_PORT}:5432
    environment:
      POSTGRES_DB: ${SE_DB_PASS}
      POSTGRES_USER: ${SE_DB_USER}
      POSTGRES_PASSWORD: ${SE_DB_PASS}
    volumes:
      - se_db:/var/lib/postgresql/data
    
  ## AI
  ## For the embedding engine
  ollama:
    volumes:
      - ai_data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    image: docker.io/ollama/ollama:latest
    ports:
      - ${OL_PORT}:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              count: all 
              capabilities: [ gpu ]
  ## Might need this for its OPENAI API            
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ai_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPENAI_PORT}:8081
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=${OPENAI_OLLAMA_HOST}:${OL_PORT} #comma separated ollama hosts
      - WEBUI_AUTH=${OPENAI_USE_AUTH}
      - WEBUI_NAME=${OPENAI_UI_NAME}
      - WEBUI_URL=${OPENAI_UI_URL}:${OPENAI_UI_PORT}
      - WEBUI_SECRET_KEY=${OPENAI_SECRET}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  tunnel-net:
    driver: bridge

volumes:
  ai_data:
  search_engine_data: