name: CORE_PORTFOLIO_STACK

services:
  local-ai:
    image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    container_name: local-ai
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - HUGGINGFACE_API_KEY=YOUR_TOKEN_HERE
      - MODELS_PATH=/models
      - DEBUG=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ai-models:/models
      - ai-backends:/backends
    ports:
      - 8000:8080
    networks:
      - core-be-net

volumes:
  ai-models:
  ai-backends:
networks:
  core-be-net:
    driver: bridge
    name: core-be-net