@API_HostAddress = http://localhost:2125

### Search for gibberish (likely no results)
GET {{API_HostAddress}}/search?q=sadsad
Accept: application/json

### Search for "Steve Irwin" using server defaults for everythin
GET {{API_HostAddress}}/search?q=Steve-Irwin
Accept: application/json

### Search for "Steve Irwin" with a limit of 20 results
GET {{API_HostAddress}}/search?q=Steve-Irwin&limit=20
Accept: application/json

### Search for "Steve Irwin" in the website "wikipedia.com"
GET {{API_HostAddress}}/search?q=Steve-Irwin&site=wikipedia.com
Accept: application/json

### Search for "Steve Irwin" in the website "wikipedia.com" with a limit of 20 results
GET {{API_HostAddress}}/search?q=Steve-Irwin&limit=20&site=wikipedia.com
Accept: application/json

### Search for "Gun" using server defaults for everything
GET {{API_HostAddress}}/search?q=Gun
Accept: application/json

### Search for "Gun" with a limit of 20 results
GET {{API_HostAddress}}/search?q=Gun&limit=20
Accept: application/json

### Search for "Gun" in the website "wikipedia.com"
GET {{API_HostAddress}}/search?q=Gun&site=wikipedia.com
Accept: application/json

### Search for "Gun" in the website "wikipedia.com" with a limit of 20 results
GET {{API_HostAddress}}/search?q=Gun&limit=20&site=wikipedia.com
Accept: application/json