@API_HostAddress = http://localhost:1234


### Submit a test sitema
GET {{API_HostAddress}}/crawler/scrape
Accept: application/json
Content-Type: application/json

### Submit a test sitema
POST {{API_HostAddress}}/crawler/scrape
Accept: application/json
Content-Type: application/json