name: PROD_SiteStack
services:
  zacharymunshaw-prod:
    image: site-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SE_DB_CONN: "host=${SE_PROD_DB_HOST};port=${SE_PROD_DB_PORT};database=${SE_PROD_DB_NAME};username=${SE_PROD_DB_USER};password=${SE_PROD_DB_PASS};"
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./Data/SeedData:/app/data
    ports:
      - 6969:${BE_PORT1}
      - 6767:${BE_PORT2}
    networks:
      - zm-prod-tunnel-net
      - zm-prod-db-net
      - zm-prod-cache-net
  
  cloudflared-prod:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-prod
    restart: always
    entrypoint: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_PROD_TOKEN}
    networks:
      - zm-prod-tunnel-net
  ## Databases
  site-db-prod:
    image: postgres:latest
    container_name: site-database
    restart: always
    command: -p ${SITE_PROD_DB_PORT}
    ports:
      - ${SITE_PROD_DB_PORT}:${SITE_PROD_DB_PORT}
    environment:
      POSTGRES_DB: ${SITE_PROD_DB_NAME}
      POSTGRES_USER: ${SITE_PROD_DB_USER}
      POSTGRES_PASSWORD: ${SITE_PROD_DB_PASS}
    volumes:
      - PROD-site-db:/var/lib/postgresql/data
    networks:
      - zm-prod-db-net
  se-db-prod:
    image: pgvector/pgvector:pg16
    container_name: search-engine-database
    restart: always
    command: -p ${SE_PROD_DB_PORT}
    ports:
      - ${SE_PROD_DB_PORT}:${SE_PROD_DB_PORT}
    environment:
      POSTGRES_DB: ${SE_PROD_DB_NAME}
      POSTGRES_USER: ${SE_PROD_DB_USER}
      POSTGRES_PASSWORD: ${SE_PROD_DB_PASS}
    volumes:
      - PROD-se-db:/var/lib/postgresql/data
    networks:
      - zm-prod-db-net

networks:
  zm-prod-tunnel-net:
    driver: bridge
  zm-prod-db-net:
    driver: bridge
  zm-prod-cache-net:
    driver: bridge

volumes:
  PROD-site-db:
  PROD-se-db:
  PROD-cache: